# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

---
name: Unit_tests

# yamllint disable-line rule:truthy
on: [push]
jobs:
  test:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
        experimental: [false]
        include:
          - ruby-version: head
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Rspec
        run: rspec --pattern "spec/**/unit/*_spec.rb"

      - name: RuboCop
        run: bundle exec rubocop
